import type { IGRPMenuItemArgs } from "@igrp/framework-next-types";

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  // ── eFatura ──────────────────────────────────────────────
  {
    id: 100,
    code: "EFATURA_VENDAS_GROUP",
    name: "Vendas",
    type: "FOLDER",
    position: 0,
    icon: "ReceiptText",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 101,
    code: "EFATURA_FATURAS_VENDA",
    name: "Faturas de Venda",
    type: "MENU_PAGE",
    position: 0,
    icon: "FileText",
    status: "ACTIVE",
    target: "_self",
    url: "faturas-venda",
    pageSlug: "faturas-venda",
    parentCode: "EFATURA_VENDAS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 102,
    code: "EFATURA_COMPRAS_GROUP",
    name: "Compras",
    type: "FOLDER",
    position: 1,
    icon: "ShoppingCart",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 103,
    code: "EFATURA_FATURAS_COMPRA",
    name: "Faturas de Compra",
    type: "MENU_PAGE",
    position: 0,
    icon: "FileInput",
    status: "ACTIVE",
    target: "_self",
    url: "faturas-compra",
    pageSlug: "faturas-compra",
    parentCode: "EFATURA_COMPRAS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 104,
    code: "EFATURA_CONFIG_GROUP",
    name: "Configurações",
    type: "FOLDER",
    position: 2,
    icon: "Settings",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 105,
    code: "EFATURA_PARAMETRIZACAO",
    name: "Parametrização",
    type: "MENU_PAGE",
    position: 0,
    icon: "SlidersHorizontal",
    status: "ACTIVE",
    target: "_self",
    url: "parametrizacao",
    pageSlug: "parametrizacao",
    parentCode: "EFATURA_CONFIG_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 106,
    code: "EFATURA_CADASTRO",
    name: "Cadastro",
    type: "MENU_PAGE",
    position: 1,
    icon: "Users",
    status: "ACTIVE",
    target: "_self",
    url: "cadastro",
    pageSlug: "cadastro",
    parentCode: "EFATURA_CONFIG_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  // ── Legacy test entries ──────────────────────────────────
  {
    id: 43,
    code: "MEU_MENU_TEST",
    name: "Meu Menu Test",
    type: "MENU_PAGE",
    position: 0,
    icon: "AppWindow",
    status: "ACTIVE",
    target: "_self",
    url: "meu-menu-test",
    pageSlug: "meu-menu-test",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 46,
    code: "TEST_MENU_GRUPO",
    name: "Test MEnu Grupo",
    type: "FOLDER",
    position: 4,
    icon: "WrapText",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 47,
    code: "TEST_PAGINA_EXTERNA",
    name: "Test Pagina Externa",
    type: "FOLDER",
    position: 0,
    icon: "AlarmClock",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 45,
    code: "TEST_MENU_EXTERNO",
    name: "Test Menu Externo",
    type: "MENU_PAGE",
    position: 3,
    icon: "ZoomIn",
    status: "ACTIVE",
    target: "_self",
    url: "test-menu-externo",
    pageSlug: "test-menu-externo",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 49,
    code: "TEST_EXTERNAL_PAGE",
    name: "Test External Page",
    type: "EXTERNAL_PAGE",
    position: 0,
    icon: "MoveUpLeft",
    status: "ACTIVE",
    target: "_blank",
    url: "https://nosi.cv",
    pageSlug: "test-external-page",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
];
