import type { IGRPMenuItemArgs } from "@igrp/framework-next-types";

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  // ── VENDA ─────────────────────────────────────────────────────
  {
    id: 100,
    code: "EFATURA_VENDAS_GROUP",
    name: "Venda",
    type: "FOLDER",
    position: 0,
    icon: "ReceiptText",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 101,
    code: "EFATURA_FATURAS_VENDA",
    name: "Fatura de Venda",
    type: "MENU_PAGE",
    position: 0,
    icon: "FileText",
    status: "ACTIVE",
    target: "_self",
    url: "faturas-venda",
    pageSlug: "faturas-venda",
    parentCode: "EFATURA_VENDAS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 201,
    code: "EFATURA_CADASTRO_CLIENTES",
    name: "Cadastro de Cliente",
    type: "MENU_PAGE",
    position: 1,
    icon: "Users",
    status: "ACTIVE",
    target: "_self",
    url: "cadastro-clientes",
    pageSlug: "cadastro-clientes",
    parentCode: "EFATURA_VENDAS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 202,
    code: "EFATURA_PRODUTOS_VENDIDOS",
    name: "Produtos Vendidos",
    type: "MENU_PAGE",
    position: 2,
    icon: "PackageCheck",
    status: "ACTIVE",
    target: "_self",
    url: "produtos-vendidos",
    pageSlug: "produtos-vendidos",
    parentCode: "EFATURA_VENDAS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  // ── COMPRA ────────────────────────────────────────────────────
  {
    id: 102,
    code: "EFATURA_COMPRAS_GROUP",
    name: "Compra",
    type: "FOLDER",
    position: 1,
    icon: "ShoppingCart",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 103,
    code: "EFATURA_FATURAS_COMPRA",
    name: "Fatura de Compra",
    type: "MENU_PAGE",
    position: 0,
    icon: "FileInput",
    status: "ACTIVE",
    target: "_self",
    url: "faturas-compra",
    pageSlug: "faturas-compra",
    parentCode: "EFATURA_COMPRAS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 203,
    code: "EFATURA_CADASTRO_FORNECEDORES",
    name: "Cadastro de Fornecedor",
    type: "MENU_PAGE",
    position: 1,
    icon: "Truck",
    status: "ACTIVE",
    target: "_self",
    url: "cadastro-fornecedores",
    pageSlug: "cadastro-fornecedores",
    parentCode: "EFATURA_COMPRAS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 204,
    code: "EFATURA_PRODUTOS_COMPRADOS",
    name: "Produtos Comprados",
    type: "MENU_PAGE",
    position: 2,
    icon: "PackagePlus",
    status: "ACTIVE",
    target: "_self",
    url: "produtos-comprados",
    pageSlug: "produtos-comprados",
    parentCode: "EFATURA_COMPRAS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  // ── CONFIGURAÇÕES ─────────────────────────────────────────────
  {
    id: 104,
    code: "EFATURA_CONFIG_GROUP",
    name: "Configurações",
    type: "FOLDER",
    position: 2,
    icon: "Settings",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 105,
    code: "EFATURA_PARAMETRIZACAO",
    name: "Parametrização",
    type: "MENU_PAGE",
    position: 0,
    icon: "SlidersHorizontal",
    status: "ACTIVE",
    target: "_self",
    url: "parametrizacao",
    pageSlug: "parametrizacao",
    parentCode: "EFATURA_CONFIG_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 111,
    code: "EFATURA_DADOS_BANCARIOS",
    name: "Dados Bancários",
    type: "MENU_PAGE",
    position: 1,
    icon: "Landmark",
    status: "ACTIVE",
    target: "_self",
    url: "dados-bancarios",
    pageSlug: "dados-bancarios",
    parentCode: "EFATURA_CONFIG_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 109,
    code: "EFATURA_EMPRESA",
    name: "Empresa",
    type: "MENU_PAGE",
    position: 2,
    icon: "Building2",
    status: "ACTIVE",
    target: "_self",
    url: "empresa",
    pageSlug: "empresa",
    parentCode: "EFATURA_CONFIG_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  // ── DASHBOARD & ANALYTICS ─────────────────────────────────────
  {
    id: 107,
    code: "EFATURA_RELATORIOS_GROUP",
    name: "Dashboard & Analytics",
    type: "FOLDER",
    position: 3,
    icon: "BarChart2",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 110,
    code: "EFATURA_DASHBOARD",
    name: "Analytics",
    type: "MENU_PAGE",
    position: 0,
    icon: "BarChart",
    status: "ACTIVE",
    target: "_self",
    url: "dashboard",
    pageSlug: "dashboard",
    parentCode: "EFATURA_RELATORIOS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  {
    id: 108,
    code: "EFATURA_RELATORIO_VENDAS",
    name: "Relatório de Vendas",
    type: "MENU_PAGE",
    position: 1,
    icon: "TrendingUp",
    status: "ACTIVE",
    target: "_self",
    url: "reports/vendas",
    pageSlug: "reports/vendas",
    parentCode: "EFATURA_RELATORIOS_GROUP",
    applicationCode: "APP_EFATURA",
    roles: [],
  },
  // ── Legacy test entries ──────────────────────────────────────
  {
    id: 43,
    code: "MEU_MENU_TEST",
    name: "Meu Menu Test",
    type: "MENU_PAGE",
    position: 0,
    icon: "AppWindow",
    status: "ACTIVE",
    target: "_self",
    url: "meu-menu-test",
    pageSlug: "meu-menu-test",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 46,
    code: "TEST_MENU_GRUPO",
    name: "Test MEnu Grupo",
    type: "FOLDER",
    position: 4,
    icon: "AlignLeft",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 47,
    code: "TEST_PAGINA_EXTERNA",
    name: "Test Pagina Externa",
    type: "FOLDER",
    position: 0,
    icon: "AlarmClock",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 45,
    code: "TEST_MENU_EXTERNO",
    name: "Test Menu Externo",
    type: "MENU_PAGE",
    position: 3,
    icon: "ZoomIn",
    status: "ACTIVE",
    target: "_self",
    url: "test-menu-externo",
    pageSlug: "test-menu-externo",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 49,
    code: "TEST_EXTERNAL_PAGE",
    name: "Test External Page",
    type: "EXTERNAL_PAGE",
    position: 0,
    icon: "MoveUpLeft",
    status: "ACTIVE",
    target: "_blank",
    url: "https://nosi.cv",
    pageSlug: "test-external-page",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
];
