spring.application.name=EFatura
spring.datasource.url=jdbc:h2:mem:efaturadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.h2.console.enabled=true

# Inclure le message d'erreur dans les reponses HTTP 4xx/5xx (dev only)
server.error.include-message=always

spring.profiles.active=development

# Mocks pour le framework IGRP (Nécessaires pour démarrer en local)
igrp.access.api.base-url=http://localhost:8081/igrp-api
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.cloud.discovery.enabled=false
