spring.application.name=EFatura
server.port=8082
spring.datasource.url=jdbc:h2:file:./data/efaturadb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;IFEXISTS=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.h2.console.enabled=false
spring.h2.console.settings.web-allow-others=false

server.error.include-message=never
server.error.whitelabel.enabled=false

spring.profiles.active=development

# Mocks pour le framework IGRP (Nécessaires pour démarrer en local)
igrp.access.api.base-url=http://localhost:8081/igrp-api
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.cloud.discovery.enabled=false
