server.port=${SERVICE_PORT:8082}
spring.config.import=optional:file:.env[.properties]

# Eureka — disabled in local dev (no Eureka server available)
eureka.client.enabled=false
spring.cloud.refresh.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Spring Cloud Kubernetes
spring.cloud.kubernetes.discovery.enabled=${KUBERNETES_DISCOVERY_ENABLED:false}

# Authentication
#spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_JWT_ISSUER}
auth.jwt.issuer=${AUTH_JWT_ISSUER:http://localhost:8081/auth}

logging.level.cv.igrp.fatura=${LOGGING_LEVEL_APP:DEBUG}

# H2 console available in development only
spring.h2.console.enabled=true